### ISSUE TITLE
[EPIC] Timeout rework

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#149]
## Environment & Session timeout

We need to think about timeout so for now i remove timeout in this [PR](https://github.com/lenra-io/application-runner/pull/303). With this change, we stop the session supervisor and all supervised genserver when the socket close, on closing we notify the Environment's Dynamicsupervisor which checks if there are still sessions using the environment, otherwise it stops itself.

For now what i think about timeout:

![Env and Session Tree](https://github.com/lenra-io/application-runner/blob/beta/docs/diagrams/app_runner_schema.drawio.svg)

- [ ] Session Genserver timeout in 5 minutes
- [ ] Environment Genserver timeout in 5 minutes
- [ ] restart type: transient (restart only if stop status are not :,normal or :shutdown)
- [ ] implement handle_info that receive :timeout, return {:stop, <status>} where status can be :normal or :shutdown,
  - [ ] :normal, stop the genserver
  - [ ] :shutdown stop the genserver and all linked genserver

In my opinion, the overall logic we need to use to properly manage timeouts is as follows: when a genserver is in timeout, we notify the corresponding supervisor who closes the session and/or the environment, depending on the context.

Here are some ideas, feel free to comment.

### Session

For the session, we can add a timeout on RouteServer and stop SessionSupervisor on the timeout, we can also keep the supervisor shutdown on the socket shutdown.
We keep the notification to the environment with Environment.DynamicSupervisor.session_stopped.

### Environment

For the environment, I think we need to add a timeout on the view server. When a view server stops, the environment is informed and if no other view server is running, we can stop the environment (and the session, but actually all sessions normally have timeout before).

### Restart ?

With this idea we can have a case where the socket is still running, but after 5 minutes the session expires and after 10 minutes it's the environment (in case we are the only person using the environment), so the user can still run the headphones, should we implement a restart for the session and / or the environment or we send an error message to inform the user about the timeout ?

**Comment by taorepoara** [comment]
@pichoemr is it outdated ?
