### ISSUE TITLE
[EPIC] Make the Lenra versions visible by the users

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#165]
Make it easy to the users to get the Lenra versions.

- [ ] Create an endpoint to get the server version
- [ ] Create an endpoint to get the devtool version
- [ ] Create an about page in the client
- [ ] Create an about page in the backoffice
- [ ] Adapt the bug version input
