### ISSUE TITLE
[EPIC] Add job queue for Lenra app CI

### ISSUE THREAD

**Issue by shiipou** [lenra-io/lenra_cli#182]
We need a new CI to remove our call to external GitLab that trigger the app build and deployments.

- [x] lenra-io/kubernetes#77
- [x] lenra-io/server#340
- [x] ~~lenra-io/kubernetes#80~~
- [x] lenra-io/server#379

**Comment by shiipou** [comment]
For the new CI, I have several feasible options:

- Use the Kubernetes Kueue custom resources: https://github.com/kubernetes-sigs/kueue
It should handle what we want for CI very well.
Pros: It is maintained by kubernetes-sigs
Cons: it is version 0.2.1

- Create a queue with Redis and a queue management pod that will launch jobs (created with suspend: true state)
Pros: We have full control over launching pods
Cons: Can become lengthy to maintain.

- Manage the queue with the server and the event-queue project created some time ago. (Or create a GenServer to manage the queue)
Pros: We have full control over the queue and can detach from Kubernetes.
Cons: Higher maintenance difficulty.

**Comment by shiipou** [comment]
As @taorepoara said : 
>     I would go for the third solution. I'm not sure that maintenance will be more complicated because we have fewer tools to maintain.
> Additionally, the event-queue project seems to allow us to manage multiple executors, so we could easily scale by launching the > number of executors we want to handle jobs.

We'll use the third option: `Manage the queue with the server and the event-queue project`

**Comment by taorepoara** [comment]
Actually, as discussed yesterday, we won't use any queue for the first version
