### ISSUE TITLE
[EPIC] Query parser operator upgrade

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#188]
## What should be done 
We need to implement more mongo query operator in query parser
All the work will be done in Query Parser.

### Query Parser workflow

ApplicationRunner receive event from mongo when data inside collection change, we notify all query_server, query_server call match? that check if the query match the following document.

### Implemented operator
Comparison operator: eq /  ne / lt / lte / gt / gte / exists
list operator: in / nin / all
logical operator: and / or / nor

### New operator 
Element
- [ ] [$type](https://www.mongodb.com/docs/manual/reference/operator/query/type/#mongodb-query-op.-type)

Logical
- [ ] [$not](https://www.mongodb.com/docs/manual/reference/operator/query/not/#mongodb-query-op.-not)

Array
- [ ] [$elemMatch](https://www.mongodb.com/docs/manual/reference/operator/query/elemMatch/#mongodb-query-op.-elemMatch)
- [ ] [$size](https://www.mongodb.com/docs/manual/reference/operator/query/size/#mongodb-query-op.-size)

Evaluation:
- [ ] [$text](https://www.mongodb.com/docs/manual/reference/operator/query/text/#mongodb-query-op.-text)
- [ ] [$where](https://www.mongodb.com/docs/manual/reference/operator/query/where/#mongodb-query-op.-where)
- [ ] [$regex](https://www.mongodb.com/docs/manual/reference/operator/query/regex/#mongodb-query-op.-regex)
- [ ] [$mod](https://www.mongodb.com/docs/manual/reference/operator/query/mod/#mongodb-query-op.-mod)
- [ ] [$jsonSchema](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#mongodb-query-op.-jsonSchema)
- [ ] [$expr](https://www.mongodb.com/docs/manual/reference/operator/query/expr/#mongodb-query-op.-expr)
