### ISSUE TITLE
[EPIC] OAuth Provider & Login

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#209]
## What should be done 
The "hard" part of this work is described here : 
https://rattle-llama-7da.notion.site/OAuth-Provider-c43ec6d6f23e47c6939166c3d594d698

- [x] lenra-io/kubernetes#91
- [x] lenra-io/server#369
- [x] lenra-io/server#370
- [x] lenra-io/server#372
- [x] lenra-io/server#373
- [x] lenra-io/server#388
- [x] lenra-io/server#389
- [x] lenra-io/server#374
- [x] lenra-io/server#375
- [x] lenra-io/client-common#82
- [x] lenra-io/client#67
- [x] lenra-io/backoffice#91
- [x] lenra-io/server#376
- [ ] lenra-io/server#377
- [x] lenra-io/server#378
- [ ] lenra-io/docs#98
- [ ] https://github.com/lenra-io/lenra_cli/issues/293
- [x] lenra-io/devtool#191

## What can be done additionally
- [ ] [Server/Client] Add the 2FA Authentication using One-Time Passcode ? (OTP)
- [ ] Add the [Webauthn](https://webauthn.io/) protocol

## Technical recommandation
Most of the complexity is handled by Ory Hydra. We will add some applications and library once to simplify the system overhaul.
Most of the security concerns are handled by Ory Hydra. Be careful with the Ory Hydra configuration to only expose specific port(s).

**Comment by Nesqwik** [comment]
@taorepoara i've created the subtask for this Epic with some description of the work that must be done.

Some of the task need some discussions and decisions about the design and/or features.
Depending of the decisions made, some other task will be created.

**Comment by taorepoara** [comment]
This epic can be closed. The remaining tasks will be managed later
