### ISSUE TITLE
[Task] Listener or action

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#234]
In many parts of our projects we use `listener` and `action` to say the same thing.

## What should be done

Define which one we will use and replace the other one in every projects (maybe deprecating it).

Linked pull requests:

*   [x] lenra-io/lenra\_ui\_runner#238
*   [x] lenra-io/components-api#152
*   [x] lenra-io/ex\_component\_schema#13
*   [x] ~lenra-io/lenra-components-lib-javascript#12~
*   [x] lenra-io/server#452
*   [x] lenra-io/devtool#200
*   [x] lenra-io/template-python#27
*   [x] lenra-io/app-lib-js#39
* [x] https://github.com/lenra-io/template-javascript/pull/23
* [x] https://github.com/lenra-io/template-typescript/pull/29
* [x] https://github.com/lenra-io/app-lib-rust/pull/5
* [x] https://github.com/lenra-io/template-rust/pull/25

**Comment by Nesqwik** [comment]
In the json representation of the UI the listeners part look like that : 
```json
{
    "type": "button",
    "text": "My button",
    "onPressed": {
        "action": "buttonPressed"
    },
}
```

And the "listener" in the docs is defined with this : 
```
action: The action name to call
```

Here, the label "name" might be more appropriate since it refer to the listener "name".
Otherwise, using "listener(s)" looks good.

**Comment by taorepoara** [comment]
> 

I think it would be clearer to use listener everywhere. I know that it's the name of the listener, but it could considered as the listener id so using "listener" instead of action or name could be easier to understand.

**Comment by taorepoara** [comment]
I understand this point of view.

I think that we'll use the `name` property for the listener definition in the views and `listener` in the listener requests just like it's done for the view component. We'll have to add a discriminant to avoid definition conflict because the `{"name": "value"}` pattern is even more common than the `{"action": "value" }` one (see https://github.com/orgs/lenra-io/discussions/313)

**Comment by Nesqwik** [comment]
To avoid collision I think it's just simpler to add a prefix to every lenra property (at least in the json views).
It create a pattern, makes it simple to distinguish which property is a lenra property or a personnal one AND makes the discriminant property useless for some cases.

For example, change this : 
```json
{
  "value": 1,
  "increment": {
     "type": "listener",
     "name": "foo",
     "props": {...}
  }
}
```
To this : 
```json
{
  "value": 1,
  "increment": {
     "_listener": "foo",
     "_props": {...}
  }
}
```

To make it simpler to use the lenra properties, the app library should take care of it anyway : 
 ```js
return {
  value: 1,
  increment: Lenra.listener("foo", {...})
}
```

**Comment by jonas-martinez** [comment]
@taorepoara Is this issue done or is there still some work to do that is not referenced here ?

**Comment by taorepoara** [comment]
> @taorepoara Is this issue done or is there still some work to do that is not referenced here ?

There is still the Rust template that I'm working on and a fix on the Bun template
