### ISSUE TITLE
[Bug]: The old PR is WIP seems deprecated

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#325]
### What happened?

Some PR have an error https://github.com/lenra-io/lenra-common/pulls

### Relevant log output

```Shell
Run shiipou/pr-is-wip-action@v1.1.0

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Resource not accessible by integration
```

EDIT:

Fixed by : 
- [x] https://github.com/lenra-io/server/issues/459
- [x] https://github.com/lenra-io/devtool/issues/202
- [x] https://github.com/lenra-io/kubernetes/issues/142
- [x] https://github.com/lenra-io/query-parser/issues/42
- [x] https://github.com/lenra-io/client-common/issues/99
- [x] https://github.com/lenra-io/lenra_ui_runner/issues/239
- [x] https://github.com/lenra-io/client/issues/96
- [x] https://github.com/lenra-io/backoffice/issues/110
- [x] https://github.com/lenra-io/client-lib-flutter/issues/9
