### ISSUE TITLE
[EPIC] Manage App Logo

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#342]
Most of the time apps have an image logo.

Allow the app creator uploading their image logo instead of using the generated  with the first letter of the name (default).

A logo can be added at the app level or at the environment level (to have a specific logo by env).

- [x] lenra-io/server#506
- [x] lenra-io/server#507
- [ ] lenra-io/client#99
- [ ] lenra-io/backoffice#124
