### ISSUE TITLE
[Epic] Manage not authenticated users

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#374]
Many apps need to display database data before the user login in (CMS, e-shops, ...).

To make that more global, we'll add a role management. Authenticated users will have the `user` role and not authenticated user will have the role `guest`. This will let us manage other roles later

Tasks:

- [x] lenra-io/api#15
- [x] https://github.com/lenra-io/api/pull/18 (additional)
- [x] lenra-io/server#539
- [x] Manage roles in views context
- [ ] lenra-io/docs#146
- [x] https://github.com/lenra-io/devtool/pull/213
- [ ] update app-libs
  - [x] https://github.com/lenra-io/app-lib-js/pull/77
  - [ ] lenra-io/app-lib-rust#12
  - [ ] lenra-io/app-lib-php#7
- [ ] Adapt client libs
  - [x] lenra-io/client-lib-js#14
  - [ ] lenra-io/client-lib-flutter#20
