### ISSUE TITLE
[EPIC] Display app list on client-store

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#68]
This follows this discussion https://github.com/lenra-io/Lenra/discussions/169.

### server
- [x] https://github.com/lenra-io/server/pull/296
- [x] https://github.com/lenra-io/server/pull/297

### client-common
- [x] https://github.com/lenra-io/client-common/pull/57

### client-store
- [x] https://github.com/lenra-io/client-store/pull/28

## Technical aspect

It has been determined that the apps where the user has an account (the apps that the user opened at least once) are those that should be displayed in this list. To fetch this list, the `mongo_user_link` schema could be used because it links a user to an environment and is created when the `on_user_first_join` listener is called on an app.
