### ISSUE TITLE
[EPIC] Handle user connection cookie lifetime

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#70]
Let the user choose if he want to keep connected with a cookie or not.

- [x] https://github.com/lenra-io/server/issues/287
- [x] https://github.com/lenra-io/client-common/issues/50
- [x] https://github.com/lenra-io/server/issues/288
