### ISSUE TITLE
App CRON listeners

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#75]
### Discussed in https://github.com/lenra-io/Lenra/discussions/137

# Tasks

- [x] https://github.com/lenra-io/application-runner/pull/252
- [ ] Create CRON Services
- [ ] Create CRON Routes + Controllers

In my opinion, we should use CRON via API for the same reasons @Nesqwik mentionned.

I started to think about the specifications. We will use the https://hexdocs.pm/crontab/readme.html crontab library on elixir to handle the cron "format" (* * * * *) and we will store the crontab informations in the database.

Here is the CRON database schema
- id
- listener_name
- environment_id
- user_id ? (facultative)
- props (map)
- cron (string) (* * * * *)
- last_run_date 
- should_run_missing_steps

Each CRON will open a new GenServer. The GenServer will get its next run date thanks to the crontab library :
```console
iex> import Crontab.CronExpression
iex> Crontab.Scheduler.get_next_run_date(~e[*/2], ~N[2017-01-01 01:01:00])
{:ok, ~N[2017-01-01 01:02:00]}
iex> Crontab.Scheduler.get_next_run_date!(~e[*/2], ~N[2017-01-01 01:01:00])
~N[2017-01-01 01:02:00]
``` 
And then execute a timer to run a function when reaching the next run date.
```elixir
timer.send_interval(3_600_000, :work)
```

Note that we can parse the cron format with this method :
```console
iex> Crontab.CronExpression.Parser.parse "* * * * *"
{:ok,
  %Crontab.CronExpression{day: [:*], hour: [:*], minute: [:*],
  month: [:*], weekday: [:*], year: [:*]}}

iex> Crontab.CronExpression.Parser.parse! "* * * * *"
%Crontab.CronExpression{day: [:*], hour: [:*], minute: [:*],
 month: [:*], weekday: [:*], year: [:*]}
```

## Running crons if the server crashes

If the server is offline for a long period of time, some cron runs might be missing and we might want to run them when the server gets back online.
For that we use the `last_run_date` field in the cron schema to keep track of the latest run date and give the possibility to the server to know how much steps he missed on a specific cron and run them.
We also add a `should_run_missing_steps` to let the developer define if the cron should run its missing steps.

## Warning

We have to be sure that the user time is properly translated to server time to avoid problems.

### We still need to think about how to trigger the listener from the genserver

Because the GenServer will not be authenticated into Lenra we need to find a way to trigger the listener properly.
