### ISSUE TITLE
Create `php` template

### ISSUE THREAD

**Issue by shiipou** [lenra-io/lenra_cli#78]
Template must run the counter app in [PHP](https://github.com/php)

We choose to use the same app for each template to help new developers to see how to implement they app when switching languages.

## Tasks to do:

Setting up the default app:
- [x] lenra-io/template-php#20
- [x] lenra-io/template-php#2
- [x] lenra-io/template-php#3
- [x] lenra-io/template-php#4
- [x] lenra-io/template-php#5
- [x] lenra-io/template-php#6
- [x] lenra-io/template-php#7
- [x] lenra-io/template-php#8
- [x] lenra-io/template-php#9
- [x] lenra-io/template-php#10

Setting up widgets:
- [x] lenra-io/template-php#11
- [x] lenra-io/template-php#12
- [x] lenra-io/template-php#13
- [x] lenra-io/template-php#14
- [x] lenra-io/template-php#15

Setting up listeners:
- [x] lenra-io/template-php#16
- [x] lenra-io/template-php#17
- [x] lenra-io/template-php#18

## Config lenra with Dofigen
- [x] lenra-io/template-php#19
