### ISSUE TITLE
Create `java-springboot` template

### ISSUE THREAD

**Issue by shiipou** [lenra-io/lenra_cli#84]
Template must run the counter app in [Java Springboot](https://spring.io/projects/spring-boot)

We choose to use the same app for each template to help new developers to see how to implement they app when switching languages.

## Tasks to do:

Setting up the default app:
- [x] lenra-io/template-java-springboot#21
- [x] lenra-io/template-java-springboot#2
- [x] lenra-io/template-java-springboot#3
- [x] lenra-io/template-java-springboot#4
- [x] lenra-io/template-java-springboot#5
- [x] lenra-io/template-java-springboot#6
- [x] lenra-io/template-java-springboot#7
- [x] lenra-io/template-java-springboot#8
- [x] lenra-io/template-java-springboot#9
- [x] lenra-io/template-java-springboot#10

Setting up widgets:
- [x] lenra-io/template-java-springboot#11
- [x] lenra-io/template-java-springboot#12
- [x] lenra-io/template-java-springboot#13
- [x] lenra-io/template-java-springboot#14
- [x] lenra-io/template-java-springboot#15

Setting up listeners:
- [x] lenra-io/template-java-springboot#17
- [x] lenra-io/template-java-springboot#18
- [x] lenra-io/template-java-springboot#19

## Config lenra with Dofigen
- [x] lenra-io/template-java-springboot#20

**Comment by taorepoara** [comment]
@jonas-martinez Can you document commands to start the project because I could not start it...

**Comment by taorepoara** [comment]
The jsonchema2pojo project does not manage oneOf so we can't use it: https://github.com/joelittlejohn/jsonschema2pojo/issues/831

I started creating a custom class generation in TypeScript.

**Comment by taorepoara** [comment]
The libs have been released and deployed to Maven Central.

The first template for Java and based on Spring Boot is ready and usable.

**Comment by jonas-martinez** [comment]
@taorepoara I can't run the template springboot, it tells me that it cannot find the io.lenra.app on jitpack. Do you know how to fix this issue?

**Comment by taorepoara** [comment]
I'll look at that this WE, but jitpack should not be needed anymore :thinking:

**Comment by taorepoara** [comment]
The test was made on the wrong branch.

**Comment by jonas-martinez** [comment]
Looks good to me.

I opened an issue for a docker problem using this project but not caused by the project itself. https://github.com/lenra-io/lenra_cli/issues/413
