### ISSUE TITLE
[EPIC] Interactive command in lenra_cli

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#86]
Create a `dev` interactive command in [lenra_cli](https://github.com/lenra-io/lenra_cli). The `dev` command builds the app, starts it and displays the app logs when you run it.

When you stop it using `Ctrl + C` it pauses the Docker Compose services and displays a list of commands that you can execute. You can run the `exit` command or make another `Ctrl + C` to stop the dev command for real. It will stop and remove the Docker Compose elements. Using the `continue` command will unpause the Docker Composes services.

When you change files (not ignored by the Docker context) the app is rebuilt and restarted.

The dev command can also have a custom app generator by defining it in the `dev` part of the lenra.yml file. This image for hotreload (no rebuilt and restart when using it, only Lenra env stop).

Task list:

- [x] https://github.com/lenra-io/lenra_cli/issues/19
- [x] https://github.com/lenra-io/lenra_cli/issues/20
- [x] https://github.com/lenra-io/lenra_cli/issues/21
- [x] https://github.com/lenra-io/lenra_cli/issues/22
- [x] https://github.com/lenra-io/lenra_cli/issues/24
- [x] https://github.com/lenra-io/lenra_cli/issues/25
- [x] https://github.com/lenra-io/lenra_cli/issues/26
- [ ] https://github.com/lenra-io/lenra_cli/issues/27
- [x] https://github.com/lenra-io/lenra_cli/issues/28
