### ISSUE TITLE
[EPIC] Create language templates

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#87]
Template must run the counter app using the choosed language.

We choose to use the same app for each template to help new developers to see how to implement they app when switching languages.

## List of planned templates (Other are welcome):
- [ ] lenra-io/lenra_cli#84
- [ ] lenra-io/lenra_cli#83
- [ ] lenra-io/lenra_cli#81
- [ ] lenra-io/lenra_cli#82
- [ ] lenra-io/lenra_cli#80
- [ ] lenra-io/lenra_cli#79
- [x] lenra-io/lenra_cli#78
- [ ] lenra-io/lenra_cli#77
- [x] lenra-io/template-v#2

## Tasks to do for each template:

Setting up the default app:
- [ ] Create `handle_manifest` function
- [ ] Create `handle_widget` function
- [ ] Create `handle_listener` function
- [ ] Create `handle_resource` function
- [ ] Create `get_document` function
- [ ] Create `create_document` function
- [ ] Create `update_document` function
- [ ] Create `delete_document` function
- [ ] Create `execute_query` function

Setting up widgets:
- [ ] root
- [ ] home
- [ ] menu
- [ ] counter
- [ ] loading
- [ ] root

Setting up listeners:
- [ ] onEnvStart
- [ ] onUserFirstJoin
- [ ] increment

## Config lenra with Dofigen
- [ ] Add `/lenra.yml` Dofigen file for template configuration
