### ISSUE TITLE
[EPIC] Lenra Contributor documentation

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#90]
This epic will aggregate all the works that must be done around the contributor documentation.

Each repository must have : 
- A readme that explain what the repository is about and link the documentation
- A documentation website (using github pages ?) that is generated form the code documentation and if possible some markdown pages.

Keep the Readme simple and general about this project. If you want to add technical informations, do it in the doc website markdown.

For example, the [Elixir doc](https://hexdocs.pm/elixir) have some [pages](https://hexdocs.pm/elixir/library-guidelines.html) that focus on some technical aspect that is not about the code itself and [module doc](https://hexdocs.pm/elixir/GenServer.html) that explain how a specific module should be used.

If possible : 
- The doc website should be usable offline (download the zip and use it offline)
- The doc website should have an offline search system
- The doc should be versionned and generated with each version 

## client-store
- [x] lenra-io/client-store#13

## client-app
- [x] lenra-io/client-app#20

## client-backoffice
- [x] lenra-io/client-backoffice#28

## client-common
- [x] https://github.com/lenra-io/client-common/issues/31
