### ISSUE TITLE
[EPIC] Make a full documentation for the developpers

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#94]
The subject that must be covered IMO : 
- How does Lenra works ? (the different parts and the connexion between them)
- How to start a new project ?
- How to develop locally ?
- The Basics of the App Lifecycle.
- How to build the interface ?
- How to interact with the UI ? (forms, input etc..)
- How to save data in the Datastore ?
- How to display data on my UI ? (query language, realtime etc..)
- How to publish my app ? (new App, publish, invite friends, make the app public...)

## components-api documentation

- [x] lenra-io/Lenra#119

## Client side documentation

- [x] https://github.com/lenra-io/Lenra/issues/121

## Other

- [ ] https://github.com/lenra-io/docs/pull/60
