### ISSUE TITLE
Create all k8s resources for automatic deployments

### ISSUE THREAD

**Issue by shiipou** [lenra-io/lenra_cli#96]
This must help for automatic deployment of every updated component of the Lenra platform.
This may also help to deploy a new kubernetes cluster in minimum of time.

- [x] https://github.com/lenra-io/kubernetes/issues/6
- [x] https://github.com/lenra-io/kubernetes/pull/1
- [x] https://github.com/lenra-io/kubernetes/pull/3
- [x] https://github.com/lenra-io/kubernetes/pull/7
- [x] https://github.com/lenra-io/kubernetes/pull/10
- [x] https://github.com/lenra-io/kubernetes/issues/9
- [x] https://github.com/lenra-io/kubernetes/issues/17
- [x] https://github.com/lenra-io/kubernetes/issues/18
- [x] https://github.com/lenra-io/kubernetes/issues/19
- [x] https://github.com/lenra-io/server/issues/124

**Comment by taorepoara** [comment]
@shiipou Is it finished ?
